// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEmo1VwUYpNoBLvj7jw5T_q2jZj4lKAg',
    appId: '1:162151556821:web:1616bedbf154576963245c',
    messagingSenderId: '162151556821',
    projectId: 'flat-finder-78412',
    authDomain: 'flat-finder-78412.firebaseapp.com',
    storageBucket: 'flat-finder-78412.appspot.com',
    measurementId: 'G-QFYDYG0EDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsbURvivE4tWeKLeBs8dpW1H_-Mgs2ldg',
    appId: '1:162151556821:android:d125189d5a4e985e63245c',
    messagingSenderId: '162151556821',
    projectId: 'flat-finder-78412',
    storageBucket: 'flat-finder-78412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQr_5wQxcgRBK2D76bhucBYmIpfL407Lw',
    appId: '1:162151556821:ios:534114bf96e67cb763245c',
    messagingSenderId: '162151556821',
    projectId: 'flat-finder-78412',
    storageBucket: 'flat-finder-78412.appspot.com',
    iosBundleId: 'com.example.flatfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQr_5wQxcgRBK2D76bhucBYmIpfL407Lw',
    appId: '1:162151556821:ios:534114bf96e67cb763245c',
    messagingSenderId: '162151556821',
    projectId: 'flat-finder-78412',
    storageBucket: 'flat-finder-78412.appspot.com',
    iosBundleId: 'com.example.flatfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsEmo1VwUYpNoBLvj7jw5T_q2jZj4lKAg',
    appId: '1:162151556821:web:1a2804543ef5011063245c',
    messagingSenderId: '162151556821',
    projectId: 'flat-finder-78412',
    authDomain: 'flat-finder-78412.firebaseapp.com',
    storageBucket: 'flat-finder-78412.appspot.com',
    measurementId: 'G-EP5QVWW6E3',
  );
}
